### Dropwizard skeleton configuration file
##
## Do not commit changes that contain credentials or sensitive data!

server:
  rootPath: /api/v1/*
  applicationConnectors:
    - type: https
      port: 8080
      keyStorePath: /path/to/development.keystore
      keyStorePassword: password
      certAlias: development
      trustStorePath: /path/to/development.truststore
      supportedProtocols:
        - TLSv1.1
        - TLSv1.2
  adminConnectors:
    - type: https
      port: 8081
      keyStorePath: /path/to/development.keystore
      keyStorePassword: password
      certAlias: development
      trustStorePath: /path/to/development.truststore
      supportedProtocols:
        - TLSv1.1
        - TLSv1.2

logging:
  loggers:
      org.hibernate.SQL: ALL
  appenders:
    - type: console
      threshold: ALL
      target: stdout
    - type: file
      currentLogFilename: logs/courses-api.log
      archivedLogFilenamePattern: logs/courses-api-%d.log.gz
      archivedFileCount: 5
      threshold: ALL
      timeZone: PST

authentication:
  - username: username
    password: password

httpDataSource:
  endpoint: https://example.com
  username: secret
  password: sauce

httpClient:
  # The socket timeout value. If a read or write to the underlying
  # TCP/IP connection hasn't succeeded after this duration, a
  # timeout exception is thrown.
  timeout: 60000ms

  # The connection timeout value. If a TCP/IP connection cannot be
  # established in this time, a timeout exception is thrown.
  connectionTimeout: 60000ms

  timeToLive: 1h
  cookiesEnabled: false
  maxConnections: 1024
  maxConnectionsPerRoute: 1024
  keepAlive: 0ms
  retries: 0
  userAgent: class-search-api
