swagger: '2.0'
info:
  title: Web API Skeleton
  description: Skeleton for Dropwizard Web APIs
  version: '1.0'
  license:
    name: GNU Affero General Public License Version 3
    url: http://www.gnu.org/licenses/agpl-3.0.en.html
externalDocs:
  description: GitHub Repository
  url: https://github.com/osu-mist/web-api-skeleton
host: localhost
schemes:
  - https
basePath: /api/v1
consumes:
  - text/plain
produces:
  - text/plain
paths:
  /:
    get:
      summary: Get information
      description: Build and runtime information about the application.
      parameters:
        - $ref: '#/parameters/pretty'
        - $ref: '#/parameters/authorization'
      responses:
        200:
          description: Object containing information
          schema:
            $ref: '#/definitions/Info'
parameters:
  authorization:
    name: Authorization
    in: header
    type: string
    required: true
    description: '"Bearer [token]" where token is your OAuth2 access token'
  pretty:
    name: pretty
    in: query
    type: boolean
    required: false
    description: If true, JSON response will be pretty-printed
definitions:
  Info:
    properties:
      meta:
        properties:
          name:
            type: string
            description: Name of the API.
          time:
            type: string
            description: Build time in ISO 8601 format.
          unixTime:
            type: integer
            description: Build time as milliseconds since the unix epoch.
          commit:
            type: string
            description: Git commit hash of the revision which was built.
          documentation:
            type: string
            description: Filename of the swagger specification for the API.
  Error:
    properties:
      status:
        type: string
        description: HTTP status code.
      links:
        properties:
          about:
            type: string
            description: A link to further information about the error.
      code:
        type: string
        description: Error code.
      title:
        type: string
        description: A short, user readable summary of the error
      detail:
        type: string
        description: A long description of the error that may contain instance-specific details.
